name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Cancel previously running PR jobs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-rust-ci:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Indicate safe directory
        ## See https://github.com/actions/checkout/issues/363
        run: git config --global --add safe.directory $(realpath .)
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - run: pre-commit run --all-files --verbose --show-diff-on-failure

  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-rust-ci:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - run: cargo check --workspace --all-targets
      - run: cargo build --workspace --all-targets
      - run: cargo test --workspace --all-targets
